# Explicit 21/W rev104 BSD-only native inputs for the portable IA-32 build.
# Do not add fmgen, GPL MAME, or excluded DOSBox FPU files.
set(NP21W_CORE_SOURCES
    ${NP21W_ROOT}/bios/bios.c
    ${NP21W_ROOT}/bios/bios09.c
    ${NP21W_ROOT}/bios/bios0c.c
    ${NP21W_ROOT}/bios/bios12.c
    ${NP21W_ROOT}/bios/bios13.c
    ${NP21W_ROOT}/bios/bios18.c
    ${NP21W_ROOT}/bios/bios19.c
    ${NP21W_ROOT}/bios/bios1a.c
    ${NP21W_ROOT}/bios/bios1b.c
    ${NP21W_ROOT}/bios/bios1c.c
    ${NP21W_ROOT}/bios/bios1f.c
    ${NP21W_ROOT}/bios/sxsibios.c
    ${NP21W_ROOT}/calendar.c
    ${NP21W_ROOT}/cbus/amd98.c
    ${NP21W_ROOT}/cbus/atapicmd.c
    ${NP21W_ROOT}/cbus/board118.c
    ${NP21W_ROOT}/cbus/board14.c
    ${NP21W_ROOT}/cbus/board26k.c
    ${NP21W_ROOT}/cbus/board86.c
    ${NP21W_ROOT}/cbus/boardpx.c
    ${NP21W_ROOT}/cbus/boardso.c
    ${NP21W_ROOT}/cbus/boardspb.c
    ${NP21W_ROOT}/cbus/boardws.c
    ${NP21W_ROOT}/cbus/boardx2.c
    ${NP21W_ROOT}/cbus/cbuscore.c
    ${NP21W_ROOT}/cbus/cbuspnp.c
    ${NP21W_ROOT}/cbus/cs4231io.c
    ${NP21W_ROOT}/cbus/ideio.c
    ${NP21W_ROOT}/cbus/mpu98ii.c
    ${NP21W_ROOT}/cbus/pc9861k.c
    ${NP21W_ROOT}/cbus/pcm86io.c
    ${NP21W_ROOT}/cbus/sasiio.c
    ${NP21W_ROOT}/cbus/scsicmd.c
    ${NP21W_ROOT}/cbus/scsiio.c
    ${NP21W_ROOT}/codecnv/eucsjis.c
    ${NP21W_ROOT}/codecnv/eucucs2.c
    ${NP21W_ROOT}/codecnv/sjiseuc.c
    ${NP21W_ROOT}/codecnv/sjisucs2.c
    ${NP21W_ROOT}/codecnv/tcswap16.c
    ${NP21W_ROOT}/codecnv/tcswap32.c
    ${NP21W_ROOT}/codecnv/textcnv.c
    ${NP21W_ROOT}/codecnv/ucs2sjis.c
    ${NP21W_ROOT}/codecnv/ucs2utf8.c
    ${NP21W_ROOT}/codecnv/utf8ucs2.c
    ${NP21W_ROOT}/common/_memory.c
    ${NP21W_ROOT}/common/bmpdata.c
    ${NP21W_ROOT}/common/lstarray.c
    ${NP21W_ROOT}/common/milstr.c
    ${NP21W_ROOT}/common/mimpidef.c
    ${NP21W_ROOT}/common/parts.c
    ${NP21W_ROOT}/common/profile.c
    ${NP21W_ROOT}/common/rect.c
    ${NP21W_ROOT}/common/strres.c
    ${NP21W_ROOT}/common/textfile.c
    ${NP21W_ROOT}/common/wavefile.c
    ${NP21W_ROOT}/debugsub.c
    ${NP21W_ROOT}/diskimage/cd/cdd_ccd.c
    ${NP21W_ROOT}/diskimage/cd/cdd_cue.c
    ${NP21W_ROOT}/diskimage/cd/cdd_iso.c
    ${NP21W_ROOT}/diskimage/cd/cdd_mds.c
    ${NP21W_ROOT}/diskimage/cd/cdd_nrg.c
    ${NP21W_ROOT}/diskimage/cddfile.c
    ${NP21W_ROOT}/diskimage/fd/fdd_bkdsk.c
    ${NP21W_ROOT}/diskimage/fd/fdd_d88.c
    ${NP21W_ROOT}/diskimage/fd/fdd_dcp.c
    ${NP21W_ROOT}/diskimage/fd/fdd_nfd.c
    ${NP21W_ROOT}/diskimage/fd/fdd_vfdd.c
    ${NP21W_ROOT}/diskimage/fd/fdd_xdf.c
    ${NP21W_ROOT}/diskimage/fddfile.c
    ${NP21W_ROOT}/diskimage/img_strres.c
    ${NP21W_ROOT}/fdd/diskdrv.c
    ${NP21W_ROOT}/fdd/fdd_mtr.c
    ${NP21W_ROOT}/fdd/newdisk.c
    ${NP21W_ROOT}/fdd/sxsi.c
    ${NP21W_ROOT}/fdd/sxsihdd.c
    ${NP21W_ROOT}/font/font.c
    ${NP21W_ROOT}/font/fontdata.c
    ${NP21W_ROOT}/font/fontfm7.c
    ${NP21W_ROOT}/font/fontmake.c
    ${NP21W_ROOT}/font/fontpc88.c
    ${NP21W_ROOT}/font/fontpc98.c
    ${NP21W_ROOT}/font/fontv98.c
    ${NP21W_ROOT}/font/fontx1.c
    ${NP21W_ROOT}/font/fontx68k.c
    ${NP21W_ROOT}/generic/cmjasts.c
    ${NP21W_ROOT}/generic/cmndraw.c
    ${NP21W_ROOT}/generic/keydisp.c
    ${NP21W_ROOT}/generic/memdbg32.c
    ${NP21W_ROOT}/generic/softkbd.c
    ${NP21W_ROOT}/generic/unasm.c
    ${NP21W_ROOT}/i386c/cpucore.c
    ${NP21W_ROOT}/i386c/cpumem.c
    ${NP21W_ROOT}/i386c/ia32/interface.c
    ${NP21W_ROOT}/i386c/ia32/ia32.c
    ${NP21W_ROOT}/i386c/ia32/cpu.c
    ${NP21W_ROOT}/i386c/ia32/cpu_io.c
    ${NP21W_ROOT}/i386c/ia32/cpu_mem.c
    ${NP21W_ROOT}/i386c/ia32/ctrlxfer.c
    ${NP21W_ROOT}/i386c/ia32/debug.c
    ${NP21W_ROOT}/i386c/ia32/disasm.c
    ${NP21W_ROOT}/i386c/ia32/exception.c
    ${NP21W_ROOT}/i386c/ia32/groups.c
    ${NP21W_ROOT}/i386c/ia32/inst_table.c
    ${NP21W_ROOT}/i386c/ia32/paging.c
    ${NP21W_ROOT}/i386c/ia32/resolve.c
    ${NP21W_ROOT}/i386c/ia32/segments.c
    ${NP21W_ROOT}/i386c/ia32/task.c
    ${NP21W_ROOT}/i386c/ia32/instructions/bin_arith.c
    ${NP21W_ROOT}/i386c/ia32/instructions/bit_byte.c
    ${NP21W_ROOT}/i386c/ia32/instructions/ctrl_trans.c
    ${NP21W_ROOT}/i386c/ia32/instructions/data_trans.c
    ${NP21W_ROOT}/i386c/ia32/instructions/dec_arith.c
    ${NP21W_ROOT}/i386c/ia32/instructions/flag_ctrl.c
    ${NP21W_ROOT}/i386c/ia32/instructions/fpu.c
    ${NP21W_ROOT}/i386c/ia32/instructions/fpu/fpdummy.c
    ${NP21W_ROOT}/i386c/ia32/instructions/mmx/mmx.c
    ${NP21W_ROOT}/i386c/ia32/instructions/mmx/3dnow.c
    ${NP21W_ROOT}/i386c/ia32/instructions/sse/sse.c
    ${NP21W_ROOT}/i386c/ia32/instructions/sse2/sse2.c
    ${NP21W_ROOT}/i386c/ia32/instructions/sse3/sse3.c
    ${NP21W_ROOT}/i386c/ia32/instructions/ssse3/ssse3.c
    ${NP21W_ROOT}/i386c/ia32/instructions/sse4/sse4_1.c
    ${NP21W_ROOT}/i386c/ia32/instructions/sse4/sse4_2.c
    ${NP21W_ROOT}/i386c/ia32/instructions/sse4a/sse4a.c
    ${NP21W_ROOT}/i386c/ia32/instructions/logic_arith.c
    ${NP21W_ROOT}/i386c/ia32/instructions/misc_inst.c
    ${NP21W_ROOT}/i386c/ia32/instructions/seg_reg.c
    ${NP21W_ROOT}/i386c/ia32/instructions/shift_rotate.c
    ${NP21W_ROOT}/i386c/ia32/instructions/string_inst.c
    ${NP21W_ROOT}/i386c/ia32/instructions/system_inst.c
    ${NP21W_ROOT}/io/artic.c
    ${NP21W_ROOT}/io/cgrom.c
    ${NP21W_ROOT}/io/cpuio.c
    ${NP21W_ROOT}/io/crtc.c
    ${NP21W_ROOT}/io/dipsw.c
    ${NP21W_ROOT}/io/dmac.c
    ${NP21W_ROOT}/io/egc.c
    ${NP21W_ROOT}/io/emsio.c
    ${NP21W_ROOT}/io/epsonio.c
    ${NP21W_ROOT}/io/fdc.c
    ${NP21W_ROOT}/io/fdd320.c
    ${NP21W_ROOT}/io/gdc.c
    ${NP21W_ROOT}/io/gdc_pset.c
    ${NP21W_ROOT}/io/gdc_sub.c
    ${NP21W_ROOT}/io/iocore.c
    ${NP21W_ROOT}/io/mouseif.c
    ${NP21W_ROOT}/io/necio.c
    ${NP21W_ROOT}/io/nmiio.c
    ${NP21W_ROOT}/io/pcidev.c
    ${NP21W_ROOT}/io/pic.c
    ${NP21W_ROOT}/io/pit.c
    ${NP21W_ROOT}/io/printif.c
    ${NP21W_ROOT}/io/serial.c
    ${NP21W_ROOT}/io/sysport.c
    ${NP21W_ROOT}/io/upd4990.c
    ${NP21W_ROOT}/keystat.c
    ${NP21W_ROOT}/lio/gcircle.c
    ${NP21W_ROOT}/lio/gline.c
    ${NP21W_ROOT}/lio/gpset.c
    ${NP21W_ROOT}/lio/gput1.c
    ${NP21W_ROOT}/lio/gscreen.c
    ${NP21W_ROOT}/lio/lio.c
    ${NP21W_ROOT}/mem/dmav30.c
    ${NP21W_ROOT}/mem/dmax86.c
    ${NP21W_ROOT}/mem/memegc.c
    ${NP21W_ROOT}/mem/memems.c
    ${NP21W_ROOT}/mem/memepp.c
    ${NP21W_ROOT}/mem/memtram.c
    ${NP21W_ROOT}/mem/memvga.c
    ${NP21W_ROOT}/mem/memvram.c
    ${NP21W_ROOT}/nevent.c
    ${NP21W_ROOT}/pccore.c
    ${NP21W_ROOT}/sound/adpcmc.c
    ${NP21W_ROOT}/sound/adpcmg.c
    ${NP21W_ROOT}/sound/beepc.c
    ${NP21W_ROOT}/sound/beepg.c
    ${NP21W_ROOT}/sound/cs4231c.c
    ${NP21W_ROOT}/sound/cs4231g.c
    ${NP21W_ROOT}/sound/fmboard.c
    ${NP21W_ROOT}/sound/getsnd/getsmix.c
    ${NP21W_ROOT}/sound/getsnd/getsnd.c
    ${NP21W_ROOT}/sound/getsnd/getwave.c
    ${NP21W_ROOT}/sound/opl3.c
    ${NP21W_ROOT}/sound/oplgenc.c
    ${NP21W_ROOT}/sound/oplgeng.c
    ${NP21W_ROOT}/sound/opna.c
    ${NP21W_ROOT}/sound/opngenc.c
    ${NP21W_ROOT}/sound/opngeng.c
    ${NP21W_ROOT}/sound/opntimer.c
    ${NP21W_ROOT}/sound/pcm86c.c
    ${NP21W_ROOT}/sound/pcm86g.c
    ${NP21W_ROOT}/sound/pcmmix.c
    ${NP21W_ROOT}/sound/psggenc.c
    ${NP21W_ROOT}/sound/psggeng.c
    ${NP21W_ROOT}/sound/rhythmc.c
    ${NP21W_ROOT}/sound/s98.c
    ${NP21W_ROOT}/sound/sndcsec.c
    ${NP21W_ROOT}/sound/sound.c
    ${NP21W_ROOT}/sound/soundrom.c
    ${NP21W_ROOT}/sound/tms3631c.c
    ${NP21W_ROOT}/sound/tms3631g.c
    ${NP21W_ROOT}/sound/ymzadpcmc.c
    ${NP21W_ROOT}/sound/ymzadpcmg.c
    ${NP21W_ROOT}/timing.c
    ${NP21W_ROOT}/vram/dispsync.c
    ${NP21W_ROOT}/vram/makegrex.c
    ${NP21W_ROOT}/vram/makegrph.c
    ${NP21W_ROOT}/vram/maketext.c
    ${NP21W_ROOT}/vram/maketgrp.c
    ${NP21W_ROOT}/vram/palettes.c
    ${NP21W_ROOT}/vram/scrndraw.c
    ${NP21W_ROOT}/vram/scrnsave.c
    ${NP21W_ROOT}/vram/sdraw.c
    ${NP21W_ROOT}/vram/vram.c
)
